Repository kiyarose/SillyLittleFiles, pull requests merged in 2024-06, with the labels that each got.

#240 [ Merge ] : Merge Security.md into cfnamechange
  SECURITY.md
Labels: documentation

#237 [ Hotfix ] : Code Factor Name Change
  .github/ISSUE_TEMPLATE/Enhancer.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  SECURITY.md
  docs/discussions/1.html
  docs/discussions/11.html
  docs/discussions/190.html
  docs/discussions/193.html
  docs/discussions/220.html
  docs/index.html
  docs/tools/directory/serverlister.html
Labels: documentation, formatting, research

#246 [ Workflow ] : Add lines to invoke tmate on WF error
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
Labels: enhancement, formatting, Internal

#243 [ Formatting ] : Organize Workflows
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/disabled/Prettier.yml
  .github/workflows/disabled/README.md
  .github/workflows/disabled/Syntaxer.yml
  .github/workflows/disabled/backup-firestore.yml
  .github/workflows/disabled/main_sillylol.yml
  .github/workflows/disabled/stale.yml
Labels: style, formatting, Internal

#265 [ Dependencies ] : Merge SLF Deps into Main
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/restyle-tag.yml
  package-lock.json
  package.json
Labels: dependencies, dependant, sillylittlefiles, Internal, github_actions, javascript

#266 [ Feature ] : Link to EZPROX in tools and RM
  README.md
  docs/tools/index.html
Labels: documentation, enhancement, help wanted, tool, style, formatting, dependant, sillylittlefiles, acprox, selfhost
