Repository kiyarose/SillyLittleFiles, pull requests merged in 2024-07, with the labels that each got.

#271 [ License ] : Update Date on license
  LICENSE
Labels: style, sillylittlefiles, Internal

#276 [ Style ] : Request Bytespider ignore crawling
  docs/robots.txt
Labels: style, sillylittlefiles, Internal

#278 [ Vers ] : Update last.version in #277
  extools/last.version
  package-lock.json
  package.json
Labels: dependencies, sillylittlefiles, Internal

#280 [ Vers ] : 13132 -> fb13133
  extools/last.version
Labels: dependencies, sillylittlefiles, Internal

#281 [ Style ] : Update SecPolicy and add COC
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation, enhancement, sillylittlefiles, Internal
